### ISSUE TITLE
Does JSON still work or do I have to switch to JAVA?

### ISSUE THREAD

**Issue by Cristian19194848** [Stypox/dicio-numbers#5]
I have almost completely translated the JSON I see that you moved to JAVA still serves that JSON?

**Comment by Stypox** [comment]
Unfortunately you need to translate Java files, too. Some Json files are just used as configuration for the Java code for parsing, see #1

**Comment by Cristian19194848** [comment]
I have been able to translate it quite a bit, that's why I left it in test instead of main.
I'm going to ask for help in xmpp and fediverse so we can translate it 100% to spanish.
Is it ok?
Sorry I almost never do these things (I'm a newbie).

**Comment by Stypox** [comment]
Yeah that's definitely fine, thanks!
